{% set version = "0.0.1" %}

package:
  name: pm4ngs
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/p/pm4ngs/pm4ngs-{{ version }}.tar.gz
  sha256: ee5a3b6a7dcf0757421dd45c1a891e3477626c5f21fcf7934d32fb66129a58b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - python >=3.7
    - poppler
    - requests

test:
  commands:
    - pm4ngs-create -v
    - pm4ngs-rnaseq -h
    - pm4ngs-chipseq -h
    - pm4ngs-chipexo -h

about:
  home: https://pypi.org/project/pm4ngs/
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: "PM4NGS generates a standard organizational structure for Next Generation Sequencing (ngs) data analysis"
  dev_url: https://github.com/ncbi/pm4ngs

extra:
  recipe-maintainers:
    - r78v10a07
